// Generated by gencpp from file ros_test_pkg/add_two_noRequest.msg
// DO NOT EDIT!


#ifndef ROS_TEST_PKG_MESSAGE_ADD_TWO_NOREQUEST_H
#define ROS_TEST_PKG_MESSAGE_ADD_TWO_NOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_test_pkg
{
template <class ContainerAllocator>
struct add_two_noRequest_
{
  typedef add_two_noRequest_<ContainerAllocator> Type;

  add_two_noRequest_()
    : a(0)
    , b(0)  {
    }
  add_two_noRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> const> ConstPtr;

}; // struct add_two_noRequest_

typedef ::ros_test_pkg::add_two_noRequest_<std::allocator<void> > add_two_noRequest;

typedef boost::shared_ptr< ::ros_test_pkg::add_two_noRequest > add_two_noRequestPtr;
typedef boost::shared_ptr< ::ros_test_pkg::add_two_noRequest const> add_two_noRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator1> & lhs, const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator1> & lhs, const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_test_pkg/add_two_noRequest";
  }

  static const char* value(const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a \n"
"int64 b \n"
;
  }

  static const char* value(const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_two_noRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_test_pkg::add_two_noRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_test_pkg::add_two_noRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TEST_PKG_MESSAGE_ADD_TWO_NOREQUEST_H
