// Generated by gencpp from file ros_test_pkg/person_data.msg
// DO NOT EDIT!


#ifndef ROS_TEST_PKG_MESSAGE_PERSON_DATA_H
#define ROS_TEST_PKG_MESSAGE_PERSON_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_test_pkg
{
template <class ContainerAllocator>
struct person_data_
{
  typedef person_data_<ContainerAllocator> Type;

  person_data_()
    : name()
    , age(0)
    , color()  {
    }
  person_data_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::ros_test_pkg::person_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_test_pkg::person_data_<ContainerAllocator> const> ConstPtr;

}; // struct person_data_

typedef ::ros_test_pkg::person_data_<std::allocator<void> > person_data;

typedef boost::shared_ptr< ::ros_test_pkg::person_data > person_dataPtr;
typedef boost::shared_ptr< ::ros_test_pkg::person_data const> person_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_test_pkg::person_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_test_pkg::person_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_test_pkg::person_data_<ContainerAllocator1> & lhs, const ::ros_test_pkg::person_data_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_test_pkg::person_data_<ContainerAllocator1> & lhs, const ::ros_test_pkg::person_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_test_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_test_pkg::person_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_test_pkg::person_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_test_pkg::person_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_test_pkg::person_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_test_pkg::person_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_test_pkg::person_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_test_pkg::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcc4ac2f30ce95ce4aadb3be7c765c64";
  }

  static const char* value(const ::ros_test_pkg::person_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcc4ac2f30ce95ceULL;
  static const uint64_t static_value2 = 0x4aadb3be7c765c64ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_test_pkg::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_test_pkg/person_data";
  }

  static const char* value(const ::ros_test_pkg::person_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_test_pkg::person_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name \n"
"uint8 age\n"
"string color\n"
;
  }

  static const char* value(const ::ros_test_pkg::person_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_test_pkg::person_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_test_pkg::person_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_test_pkg::person_data_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TEST_PKG_MESSAGE_PERSON_DATA_H
